version: "3"
networks:
  app_network: null
services:
  app:
    build:
      context: ./app
      dockerfile: ../.docker/app.dockerfile
    working_dir: /app
    volumes:
      - "./app:/app"
    ports:
      - 3000:3000
    networks:
      - app_network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ../.docker/api.dockerfile
    working_dir: /api
    volumes:
      - "./api:/api"
    ports:
      - 5000:80
    networks:
      - app_network
    restart: unless-stopped
